### ISSUE TITLE
New Day

### ISSUE THREAD

**Issue by Afrosiyob** [web-developer04/axios#6]
.... mana

**Comment by web-developer04** [comment]
Ok

**Comment by Afrosiyob** [comment]
Bilmadim savollarga turi javob berdimmi yumi no rostini etdim ... variantlar yuligigq ozgina qiynaldim 😏😁

**Comment by web-developer04** [comment]
Rostini aytganizdan xursandman.

**Comment by Afrosiyob** [comment]
Ha mayli ... kuningiz ajoyib utsin ... ishga borvotudim...

**Comment by web-developer04** [comment]
Ok. Have a good day

**Comment by Afrosiyob** [comment]
Telegramda gaplasholimizmi??

**Comment by Afrosiyob** [comment]
Hayrli kun😊

**Comment by Afrosiyob** [comment]
🤔🤨🤨🤨

**Comment by Afrosiyob** [comment]
Ok, I got you...😏

**Comment by web-developer04** [comment]
Ok

**Comment by web-developer04** [comment]
Yangilik yu. Òqishlar yaxshii. Hali 2chi semestr boshlanmadi

**Comment by Afrosiyob** [comment]
Hmmm ingliz  tili boshladizmi diman.... 😁.... etgancha okez qali nmalar qivotti yaxshimj

**Comment by Afrosiyob** [comment]
Ancha buludi gaplashmaganimga

**Comment by web-developer04** [comment]
> Hmmm ingliz tili boshladizmi diman.... 😁.... etgancha okez qali nmalar qivotti yaxshimj

Xa boshladim. Xa yaxshilar Allohga shukr

**Comment by Afrosiyob** [comment]
Qachon topshirmoqchisiz ielts????

**Comment by web-developer04** [comment]
Shu yil oxiri yoki kelasi yil boshi

**Comment by Afrosiyob** [comment]
Etgancha qaysi yunalishda uqivotudis ?

**Comment by web-developer04** [comment]
Logistika

**Comment by Afrosiyob** [comment]
> Shu yil oxiri yoki kelasi yil boshi

Uhooo zuru Hudo holasa 7 8 9 ovosez .... yoki 4 5 planmi 😁😁😁

**Comment by Afrosiyob** [comment]
Uhooo😂😂🤣🤣🤣🤣 ok ielts  ga zakas beramiza bumasa 10 11 ball larni ham chiqarishsin endi a

**Comment by Afrosiyob** [comment]
> > > Shu yil oxiri yoki kelasi yil boshi
> > 
> > 
> > Uhooo zuru Hudo holasa 7 8 9 ovosez .... yoki 4 5 planmi 😁😁😁
> 
> E maydalashishni xoxlamimanuu. Pan 10dee😁😁

Manabu man bilgan shogirt😊😁💪💪💪 sal qoldi man boshqasi bilan gaplashvomman dep uylavotudim😏😁

**Comment by Afrosiyob** [comment]
Etgancha tuzgan spiskez esizdami oladigan narsalariz bor ediku....

**Comment by web-developer04** [comment]
> > > > Shu yil oxiri yoki kelasi yil boshi
> > > 
> > > 
> > > Uhooo zuru Hudo holasa 7 8 9 ovosez .... yoki 4 5 planmi 😁😁😁
> > 
> > 
> > E maydalashishni xoxlamimanuu. Pan 10dee😁😁
> 
> Manabu man bilgan shogirt😊😁💪💪💪 sal qoldi man boshqasi bilan gaplashvomman dep uylavotudim😏😁

😎😎mendaa uu

**Comment by web-developer04** [comment]
Kubic yiģishni ham òrgandim 3x3ni

**Comment by Afrosiyob** [comment]
🙄😢😔😔😔kubik terishni ham urgandizmi urgataman degandim uziz urganibsizde

**Comment by Afrosiyob** [comment]
> > Etgancha tuzgan spiskez esizdami oladigan narsalariz bor ediku....
> 
> Kòpini oldim. Bilasizu mayda narsalar kòp edi. Fleshka komp tel, 🎧 headphones, naushnik, player, kubic..

Hooo chaqqonoy😁😁😁 molodets lekin kuchli kuchli .... etmapsizam spiskani bajarvotganizzi😏😊🤗

**Comment by web-developer04** [comment]
> 🙄😢😔😔😔kubik terishni ham urgandizmi urgataman degandim uziz urganibsizde

Òzizu blocklagan😏

**Comment by web-developer04** [comment]
> Man hechnma qimadim spiskaha qilomadim😑 haykalga ushab qovomman

Ii MACchi. Bram kamtarsizee. Zato siz ishlisiz òziz pul topasiz. Hatto uyizdagilaga jònatasiz. Menchi faqat òqiman

**Comment by Afrosiyob** [comment]
> > 🙄😢😔😔😔kubik terishni ham urgandizmi urgataman degandim uziz urganibsizde
> 
> Òzizu blocklagan😏

😖🙈 eslamelik uyalib ketvomman

**Comment by Afrosiyob** [comment]
> > Man hechnma qimadim spiskaha qilomadim😑 haykalga ushab qovomman
> 
> Ii MACchi. Bram kamtarsizee. Zato siz ishlisiz òziz pul topasiz. Hatto uyizdagilaga jònatasiz. Menchi faqat òqiman

Yugeee sizga havasim keladi qiziqishiz buyicha uqisiz doim intilasiz bilasiz urganasiz

**Comment by Afrosiyob** [comment]
Ok abedlanib oling yaxshlab keyin gaplashamiza 😊😊😊 yoqimli ishtahap

**Comment by Afrosiyob** [comment]
Qaribman😭😭😭😭😭 footbol uynagandim charchab qoldim

**Comment by web-developer04** [comment]
> Ok abedlanib oling yaxshlab keyin gaplashamiza 😊😊😊 yoqimli ishtaha
You too

**Comment by web-developer04** [comment]
> Ok abedlanib oling yaxshlab keyin gaplashamiza 😊😊😊 yoqimli ishtahap

You too

**Comment by Afrosiyob** [comment]
> > Vohtiz bor yoshsiz kuniz zur utadi....🤗😊😊 man sezme qolaman qando kun utvotganini
> 
> Iii skateboard uchmayapsizmi? Siz ham mendan qolishmisizuu master

Master😢😭🙈 chang shunchaki chang

**Comment by web-developer04** [comment]
> Qaribman😭😭😭😭😭 footbol uynagandim charchab qoldim

Doimiy òynab turmaganizga shunaqa bòlgan. Bu hech qanaqa qarilik emas!!!

**Comment by Afrosiyob** [comment]
> > Qaribman😭😭😭😭😭 footbol uynagandim charchab qoldim
> 
> Doimiy òynab turmaganizga shunaqa bòlgan. Bu hech qanaqa qarilik emas!!!

Qatdan bildiz 🤔🤔🤨 uynamasligimmi demoqchi edim... mani uji yodlab bugansizu esimdan chiqibti😁

**Comment by web-developer04** [comment]
> > > Vohtiz bor yoshsiz kuniz zur utadi....🤗😊😊 man sezme qolaman qando kun utvotganini
> > 
> > 
> > Iii skateboard uchmayapsizmi? Siz ham mendan qolishmisizuu master
> 
> Biza doim yoshmiz bilimga chanqoq hushchaqchaq doim bahor😁💪💪💪

Oo ana endi òzizga keldiiiz👍

**Comment by Afrosiyob** [comment]
> > > > Vohtiz bor yoshsiz kuniz zur utadi....🤗😊😊 man sezme qolaman qando kun utvotganini
> > > 
> > > 
> > > Iii skateboard uchmayapsizmi? Siz ham mendan qolishmisizuu master
> > 
> > 
> > Biza doim yoshmiz bilimga chanqoq hushchaqchaq doim bahor😁💪💪💪
> 
> Oo ana endi òzizga keldiiiz👍

😁😁manimcha sizdan ham yosh busam kere 1 2 oyga

**Comment by web-developer04** [comment]
> > > > > Vohtiz bor yoshsiz kuniz zur utadi....🤗😊😊 man sezme qolaman qando kun utvotganini
> > > > 
> > > > 
> > > > Iii skateboard uchmayapsizmi? Siz ham mendan qolishmisizuu master
> > > 
> > > 
> > > Biza doim yoshmiz bilimga chanqoq hushchaqchaq doim bahor😁💪💪💪
> > 
> > 
> > Oo ana endi òzizga keldiiiz👍
> 
> 😁😁manimcha sizdan ham yosh busam kere 1 2 oyga

Balkii lkn men 5 6 yil kichkinaligim aniq sizdan😏

**Comment by Afrosiyob** [comment]
> > > > > > Vohtiz bor yoshsiz kuniz zur utadi....🤗😊😊 man sezme qolaman qando kun utvotganini
> > > > > 
> > > > > 
> > > > > Iii skateboard uchmayapsizmi? Siz ham mendan qolishmisizuu master
> > > > 
> > > > 
> > > > Biza doim yoshmiz bilimga chanqoq hushchaqchaq doim bahor😁💪💪💪
> > > 
> > > 
> > > Oo ana endi òzizga keldiiiz👍
> > 
> > 
> > 😁😁manimcha sizdan ham yosh busam kere 1 2 oyga
> 
> Balkii lkn men 5 6 yil kichkinaligim aniq sizdan😏

😡😡😡

**Comment by web-developer04** [comment]
> > > > > > > Vohtiz bor yoshsiz kuniz zur utadi....🤗😊😊 man sezme qolaman qando kun utvotganini
> > > > > > 
> > > > > > 
> > > > > > Iii skateboard uchmayapsizmi? Siz ham mendan qolishmisizuu master
> > > > > 
> > > > > 
> > > > > Biza doim yoshmiz bilimga chanqoq hushchaqchaq doim bahor😁💪💪💪
> > > > 
> > > > 
> > > > Oo ana endi òzizga keldiiiz👍
> > > 
> > > 
> > > 😁😁manimcha sizdan ham yosh busam kere 1 2 oyga
> > 
> > 
> > Balkii lkn men 5 6 yil kichkinaligim aniq sizdan😏
> 
> 😡😡😡

😝😝😝

**Comment by Afrosiyob** [comment]
Kulish busa a 🧐 mayli hardoimgide mojnaku😏

**Comment by Afrosiyob** [comment]
Essiz stikerlarsiz qiziq bumas ekan 😑😔

**Comment by Afrosiyob** [comment]
> > Vohtiz bor yoshsiz kuniz zur utadi....🤗😊😊 man sezme qolaman qando kun utvotganini
> 
> Iii skateboard uchmayapsizmi? Siz ham mendan qolishmisizuu master

**Comment by Afrosiyob** [comment]
Macda edim uyga keludim reopen qilaman dep close qivoribman

**Comment by web-developer04** [comment]
👍👍👍

**Comment by Afrosiyob** [comment]
Baribir jahliz chiqdiya

**Comment by Afrosiyob** [comment]
Shitta tovo yoki uqlov yetishmadide
